"""Initial tables

Revision ID: 254ed727a717
Revises: 
Create Date: 2025-11-09 11:58:37.612664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '254ed727a717'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.BigInteger(), nullable=False),
    sa.Column('price_high', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('price_low', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('price_close', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('price_open', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['symbol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_datetime'), 'user', ['datetime'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_datetime'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
