"""Init

Revision ID: 35a68bdd11a9
Revises: 69c2f3279631
Create Date: 2025-11-12 22:59:37.004597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35a68bdd11a9'
down_revision: Union[str, Sequence[str], None] = '69c2f3279631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests_usage', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_requests_usage_id'), table_name='requests_usage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_requests_usage_id'), 'requests_usage', ['id'], unique=False)
    op.alter_column('requests_usage', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
