"""Init

Revision ID: 69c2f3279631
Revises: bc5872885273
Create Date: 2025-11-12 18:04:20.648397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69c2f3279631'
down_revision: Union[str, Sequence[str], None] = 'bc5872885273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('requests_number', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'user_id')
    )
    op.create_index(op.f('ix_requests_usage_id'), 'requests_usage', ['id'], unique=False)
    op.create_index(op.f('ix_requests_usage_requests_number'), 'requests_usage', ['requests_number'], unique=False)
    op.create_index(op.f('ix_requests_usage_user_id'), 'requests_usage', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requests_usage_user_id'), table_name='requests_usage')
    op.drop_index(op.f('ix_requests_usage_requests_number'), table_name='requests_usage')
    op.drop_index(op.f('ix_requests_usage_id'), table_name='requests_usage')
    op.drop_table('requests_usage')
    # ### end Alembic commands ###
