"""Create a table for hour data

Revision ID: 6e5ed3d7745a
Revises: f7bb874d79f2
Create Date: 2026-01-03 21:53:19.801433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e5ed3d7745a'
down_revision: Union[str, Sequence[str], None] = 'f7bb874d79f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticker_rate_hour',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.BigInteger(), nullable=False),
    sa.Column('price_high', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('price_low', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('price_close', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('price_open', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['symbol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticker_rate_hour_datetime'), 'ticker_rate_hour', ['datetime'], unique=False)
    op.create_index(op.f('ix_ticker_rate_hour_id'), 'ticker_rate_hour', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticker_rate_hour_id'), table_name='ticker_rate_hour')
    op.drop_index(op.f('ix_ticker_rate_hour_datetime'), table_name='ticker_rate_hour')
    op.drop_table('ticker_rate_hour')
    # ### end Alembic commands ###
