"""init

Revision ID: 77e59d209813
Revises: 
Create Date: 2025-11-13 17:06:04.673541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77e59d209813'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('requests_number', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symbol',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('provider_code', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbol_code'), 'symbol', ['code'], unique=True)
    op.create_index(op.f('ix_symbol_id'), 'symbol', ['id'], unique=False)
    op.create_index(op.f('ix_symbol_name'), 'symbol', ['name'], unique=False)
    op.create_index(op.f('ix_symbol_provider_code'), 'symbol', ['provider_code'], unique=True)
    op.create_index(op.f('ix_symbol_type'), 'symbol', ['type'], unique=False)
    op.create_table('ticker_rate_day',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.BigInteger(), nullable=False),
    sa.Column('price_high', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('price_low', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('price_close', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('price_open', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['symbol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticker_rate_day_datetime'), 'ticker_rate_day', ['datetime'], unique=False)
    op.create_index(op.f('ix_ticker_rate_day_id'), 'ticker_rate_day', ['id'], unique=False)
    op.create_table('ticker_rate_minute',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.BigInteger(), nullable=False),
    sa.Column('price_high', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('price_low', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('price_close', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('price_open', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['symbol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticker_rate_minute_datetime'), 'ticker_rate_minute', ['datetime'], unique=False)
    op.create_index(op.f('ix_ticker_rate_minute_id'), 'ticker_rate_minute', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticker_rate_minute_id'), table_name='ticker_rate_minute')
    op.drop_index(op.f('ix_ticker_rate_minute_datetime'), table_name='ticker_rate_minute')
    op.drop_table('ticker_rate_minute')
    op.drop_index(op.f('ix_ticker_rate_day_id'), table_name='ticker_rate_day')
    op.drop_index(op.f('ix_ticker_rate_day_datetime'), table_name='ticker_rate_day')
    op.drop_table('ticker_rate_day')
    op.drop_index(op.f('ix_symbol_type'), table_name='symbol')
    op.drop_index(op.f('ix_symbol_provider_code'), table_name='symbol')
    op.drop_index(op.f('ix_symbol_name'), table_name='symbol')
    op.drop_index(op.f('ix_symbol_id'), table_name='symbol')
    op.drop_index(op.f('ix_symbol_code'), table_name='symbol')
    op.drop_table('symbol')
    op.drop_table('requests_usage')
    # ### end Alembic commands ###
