"""Create ticker rate table for week and month

Revision ID: 8c3eb0d0d758
Revises: 6e5ed3d7745a
Create Date: 2026-01-07 22:32:40.564318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c3eb0d0d758'
down_revision: Union[str, Sequence[str], None] = '6e5ed3d7745a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticker_rate_month',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.BigInteger(), nullable=False),
    sa.Column('price_high', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('price_low', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('price_close', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('price_open', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['symbol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticker_rate_month_datetime'), 'ticker_rate_month', ['datetime'], unique=False)
    op.create_index(op.f('ix_ticker_rate_month_id'), 'ticker_rate_month', ['id'], unique=False)
    op.create_table('ticker_rate_week',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.BigInteger(), nullable=False),
    sa.Column('price_high', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('price_low', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('price_close', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('price_open', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['symbol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticker_rate_week_datetime'), 'ticker_rate_week', ['datetime'], unique=False)
    op.create_index(op.f('ix_ticker_rate_week_id'), 'ticker_rate_week', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticker_rate_week_id'), table_name='ticker_rate_week')
    op.drop_index(op.f('ix_ticker_rate_week_datetime'), table_name='ticker_rate_week')
    op.drop_table('ticker_rate_week')
    op.drop_index(op.f('ix_ticker_rate_month_id'), table_name='ticker_rate_month')
    op.drop_index(op.f('ix_ticker_rate_month_datetime'), table_name='ticker_rate_month')
    op.drop_table('ticker_rate_month')
    # ### end Alembic commands ###
