"""Init

Revision ID: bc5872885273
Revises: 254ed727a717
Create Date: 2025-11-09 12:02:38.625047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc5872885273'
down_revision: Union[str, Sequence[str], None] = '254ed727a717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticker_rate_minute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.BigInteger(), nullable=False),
    sa.Column('price_high', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('price_low', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('price_close', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('price_open', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['symbol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticker_rate_minute_datetime'), 'ticker_rate_minute', ['datetime'], unique=False)
    op.create_index(op.f('ix_ticker_rate_minute_id'), 'ticker_rate_minute', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticker_rate_minute_id'), table_name='ticker_rate_minute')
    op.drop_index(op.f('ix_ticker_rate_minute_datetime'), table_name='ticker_rate_minute')
    op.drop_table('ticker_rate_minute')
    # ### end Alembic commands ###
